### ISSUE TITLE
Add support for text-summary

### ISSUE THREAD

**Issue by soumak77** [personality-insights/trait-info#10]
Is there any objection to having this module also wrap https://github.com/personality-insights/text-summary?

After adding the `getFacet` api to the **text-summary** module, my code now pulls trait information from two separate modules.  It would be nice if I only needed to use the **trait-info** module to get this information.

**Comment by germanattanasio** [comment]
@aprilwebster ^^

**Comment by germanattanasio** [comment]
@aprilwebster 😒

**Comment by soumak77** [comment]
This is no longer necessary for me.  Reopen if desired.
