### ISSUE TITLE
Error with create-react-app

### ISSUE THREAD

**Issue by dionalfa** [personality-insights/trait-info#11]
Hi Watson Team,
Related to this issue: https://github.com/personality-insights/trait-info/issues/3

I think I still got the same issue as @getflixfaisal.
I am using trait-info@3.0.4 too.

Thank you

**Comment by germanattanasio** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a set of reproducible steps. Check the CONTRIBUTING.md for an example.
